version: '3'
services:
  flask:
    image: flask
    container_name: flask
    volumes:
      - ./db/flask:/app
    build:
      context: .
      dockerfile: Dockerfile-flask
    depends_on:
      - mongodb_container

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${PORT}:80
    depends_on:
      - flask
      
  mongodb_container:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27011:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/mongo:/data/db


